source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

pod 'Sprout', :path => '..'
pod 'Crashlytics', '~> 3.8'

target 'SproutLib' do
  target 'SproutLibTests' do
    inherit! :search_paths
  end
end
