source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'
use_frameworks!

pod 'Sprout', :path => '..'
pod 'AppCenter/Core', '~> 4.3'

target 'SproutLib' do
  target 'SproutLibTests' do
    inherit! :search_paths
  end
end
